### ISSUE TITLE
Noting this about the "Krabby Patty" font

### ISSUE THREAD

**Issue by toonjoey** [ctrlcctrlv/some-time-later#1]
I'm 99% sure it's as accurate that we'll ever get (besides this). It was found in the game files for "Spongebob Operation:Krabby Patty", ripped, and put online.

**Comment by ctrlcctrlv** [comment]
Things to note about _Operation Krabby Patty_:
- It was not made by the same people who made the cartoon, its author was THQ, a third party developer who at the time was the favorite in the industry for making games with movie/TV intellectual property;
- The most common screen resolution in 2001 was [800x600](http://www.w3schools.com/browsers/browsers_display.asp), stretched to 20" or so: you simply can't see all the tracing artifacts at that size;
- I have reason to doubt the font was even used in the game - it was likely an artifact from an earlier point in development. Fonts at the time didn't support multiple colors like this (even now FreeType doesn't support color emoji by default). Sure, they could have applied an algorithm to the font at run time to make these letters, but most games of the period had all of the font data as graphical assets - it's faster. ![s](https://i.ytimg.com/vi/yk9a_J3J2CA/maxresdefault.jpg)
- OKP's font and the cartoon deviate significantly. Look at the credits of the cartoon: The "p" descends below the baseline. The "s" and "i" are sized appropriately. Then look at OKP's font: "p" on the baseline, way too large "s", many other defects.

My font is more true to the cartoon font as seen in the credits and title cards. Perhaps OKP is more "official", but I consider the font made for OKP to be just that, a font for a very narrow purpose, screen graphics in a 15 year old game made in a hurry and with little regard to the possibility of better displays.

**Comment by toonjoey** [comment]
Well remember--what I know is what I remember. My memory's not gonna be the most accurate thing ever, but I'll try to be.

**Comment by ctrlcctrlv** [comment]
Did you rip Krabby Patty? I don't want you to see this font as an attack on you or your work. Both versions can co exist just fine. :)

**Comment by toonjoey** [comment]
Oh, me? Nah, I just wanted to speak my mind a little.

Anyway, yeah it was sort of from O:KP.

> Krabby Patty is a conversion of the main font as seen on SpongeBob SquarePants. It was made using the graphics from the "Operation Krabby Patty" PC game.

**Comment by ctrlcctrlv** [comment]
Yeah, that's really the problem. It's a "conversion" of raster graphics. :( 

That's why the edges are so messed up, look at the "a" and "Z" especially. Being that I've worked on a few fonts, I know a lot about automatic tracing since I often use it as a base for my work. But I never use it as my output product.

It would look fine on a 800x600 screen, but it looks awful at 72pts on a 4K display.

**Comment by toonjoey** [comment]
I never worked on a font actually...this is a new experience for me.

**Comment by FullstackJack** [comment]
No where to leave this comment, but thank you so much for making this! This font is amazing!

**Comment by ctrlcctrlv** [comment]
You're welcome! :smiley_cat:
