### ISSUE TITLE
spaced characters and Looking of hebrew letters

### ISSUE THREAD

**Issue by VogiNaBogi** [ctrlcctrlv/some-time-later#12]
Hello. Is it just me? or is it the "%" and greek symbol omega is more spaced?
AND THE HEBREW LETTER ALEPH DOES LOOK LIKE A "K'?

**Comment by ctrlcctrlv** [comment]
that's how aleph is often written.

need examples in context to reopen

**Comment by VogiNaBogi** [comment]
Reopen this. And the spaces on the letters, I mean the kerning on some
characters like "%" and greek omrga symbol looks very far. Can you fix the
kerning on sone letters?

**Comment by VogiNaBogi** [comment]
Oh! Sorry for the spelling, I actually speak spanish and i'm learning
english.

**Comment by ctrlcctrlv** [comment]
take screenshots proving an issue exists, mentioning what OS/program is used, and i will look into.

but if the OS/program is nonfree then unfortunately i can't so please try it in GIMP or Inkscape.

**Comment by VogiNaBogi** [comment]
Ok, I will try.
