### ISSUE TITLE
Hiragana / Katakana / Roadmap

### ISSUE THREAD

**Issue by Luca090902** [ctrlcctrlv/some-time-later#2]
Hello, can you add Hiragana and Katakana letters?
I like the Japanese letters.
Please tell the coming changes and characters.
I'm since years interested on the SpongeBob font.

**Comment by ctrlcctrlv** [comment]
Hello! Thank you for your interest. I have no plan to add Japanese characters to the font, unfortunately; unless you have a clear scan of some canon material that shows Japanese characters that would fit into the font. All the Japanese material I've seen are just normal fonts, not custom ones made for SpongeBob.

**Comment by Luca090902** [comment]
Please tell the coming changes and characters.
I'm interested on future plans of this font.

**Comment by ctrlcctrlv** [comment]
Thank you for your interest. *There are no future plans.* I consider the font complete. The font supports most of the world's languages; in my view there is nothing else to do.

**Comment by SpongeFontFan** [comment]
> Hello! Thank you for your interest. I have no plan to add Japanese characters to the font, unfortunately; unless you have a clear scan of some canon material that shows Japanese characters that would fit into the font. All the Japanese material I've seen are just normal fonts, not custom ones made for SpongeBob.

Then what about these?
https://static.wikia.nocookie.net/spongebob/images/6/64/ClearSBJapannetflixlogo.png/revision/latest?cb=20211003020935
https://static.wikia.nocookie.net/spongebob/images/4/43/JPN.png/revision/latest/scale-to-width-down/853?cb=20170730182532
Don't those images I linked have SpongeBob-styled fonts of Katakana? If not, why or how?

Also, I apologize if i'm wrongfully necroposting here. It's just that I wanted to find a SpongeBob Font for both Hiragana & Katakana, but came across this thread as one of the fewer results, so my apologies in advance again, if i'm wrong to be necroposting here, just want your opinion on the Japanese Fonts from those images that i've linked.
