### ISSUE TITLE
Russian phrase in README

### ISSUE THREAD

**Issue by rellikmil** [ctrlcctrlv/some-time-later#3]
Please write correctly "У меня было много веселья делает кириллический набор символов. НАСЛАЖДАТЬСЯ! Моя семья на самом деле украинский лол"
In true Russian "Мне было очень весело делать кириллицу. Наслаждайся. моя семья на самом деле из Украины лол."

**Comment by rellikmil** [comment]
И да, привет из России (Greetings from Russia), также спасибо за шрифт.

**Comment by ctrlcctrlv** [comment]
Thanks for the comment, but unfortunately I lost the original from which the version 2 readme was generated, so I can't fix it without rewriting the whole thing, which I have no time to do. 

Greetings from the Philippines :smile: :philippines:
